---
- name: "Prepare thirdparties"
  hosts: all
  gather_facts: no
  tasks:
    - name: "Install 3parties with apt"
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - apache2
        - mysql-server
        - php
        - libapache2-mod-php
        - php-mysql
